### ISSUE TITLE
Remove license from readme

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/deep-import#5]
https://github.com/CEHR2005/deep-import/blob/a9930b9c0434e820f3c2b34ec3ad9c85f478f7df/README.md?plain=1#L43-L44

We already have license showed in npm and github. Why do we need to write about it in readme? :)

**Comment by CEHR2005** [comment]
![image](https://github.com/CEHR2005/deep-import/assets/8792220/7d5ac659-43d5-4d4e-b2da-b0634b4b76cb)
